source 'https://rubygems.org'
ruby '2.0.0'

gem 'activeadmin'
gem 'aws-sdk'
gem 'coffee-rails'
gem 'devise'
gem 'dropbox-api'
gem 'figaro'
gem 'foreman'
gem 'haml'
gem 'high_voltage'
gem 'jbuilder'
gem 'jquery-rails'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-dropbox'
gem 'paperclip'
gem 'pg'
gem 'puma'
gem 'rails', '3.2.13'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'dust-rails'


group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '~> 4.0.0'
  gem 'guard'
  gem 'guard-spork'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'mailcatcher'
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'meta_request'
  gem 'fakeweb'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end
